# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 高新区图书馆文化馆年鉴 # ex. I m Chuan
subtitle: 高新区图书馆文化馆
name: 高新区图书馆文化馆 # ex. DONGChuan
email: 824732471@qq.com
location: My location # ex. Nice, France
company: MyCompany
company_url: my_company_website
github_url: https://github.com/shenshanwohu # ex. https://github.com/DONGChuan
github_username: shenshanwohu # ex. DONGChuan
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: shenshanwohu.github.io/gaoxin.github.io # ex. DONGChuan/DONGChuan.github.io
encoding: "utf-8"


# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://shenshanwohu.github.io/gaoxin.github.io       #https://shenshanwohu.github.io/gaoxin.github.io  http://localhost:4000
## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: coderay
  syntax_highlighter_opts: {}

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /gaoxin.github.io/
    label: 首页

  -
    href: /gaoxin.github.io/pdf
    label: 10-18年鉴

  -
    href: /gaoxin.github.io/yearbook
    label: 07-09年鉴

 # -
    # href: /bookmark
    # label: Bookmark


  -
    # href: /about
    # label: About
    href: /gaoxin.github.io/archives
    label: 年鉴直达

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
