source 'https://gems.ruby-china.com/'

gem 'json', github: 'flori/json', branch: 'v1.8'
gem 'rough'
gem 'jekyll-paginate'
gem 'jekyll-geo-pattern'
gem 'kramdown'
gem 'jekyll-github-metadata'
gem 'did_you_mean', '~> 1.4'
gem 'fileutils', '~> 1.4', '>= 1.4.1'
gem 'jekyll-octicons'
gem 'date'
gem 'kramdown-syntax-coderay', '~> 1.0', '>= 1.0.1'